doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    use_savepoints: true
    server_version: '10.6.16-mariadb'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      string_functions:
        json_contains: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
      numeric_functions:
        convert_money_to_int: App\DQL\ConvertMoneyToInt
    enable_lazy_ghost_objects: true