version: '3.9'
name: 'ares'
services:
  db:
    image: mariadb:10.6.16
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql:delegated
    ports:
      - "${DB_PORT}:3306"
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    restart: unless-stopped
    depends_on:
      - db
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
      target: base
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?serverVersion=mariadb-10.6.16
      FIRST_RUN: ${FIRST_RUN:-0}
      XDEBUG_CONFIG: ${XDEBUG_IDE}
    command: ["symfony", "server:start", "--no-tls"]
    restart: on-failure:2
    volumes:
      - ../:/var/www
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
volumes:
  database:
